### ISSUE TITLE
[BUG] Missing images in some News

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [michael-mosler/Pius-App-Gateway#6]
**Describe the bug**
The "News" WebView does not show the image sometimes

**Screenshots**
![Screenshot_20201130-185400](https://user-images.githubusercontent.com/44142235/100645836-89a14000-333d-11eb-8a5f-aa630fb7bf8b.jpg)

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro
 - OS: Android 10
 - Version 1.6

**Additional context**
Error is probably in Webview: Image is not shown if accessing the back-end via browser but it is normally displayed in Insomnia REST.

**Comment by michael-mosler** [comment]
Actually images are not missing but are not rendered correctly. As in original implementation images are now removed again on server side.
